# SearXNG settings

# most of the engines being removed here have been removed
# due to highly NSFW results as a result of normal/typical
# search queries, making them practically russian roulette
use_default_settings:
  engines:
    remove:
      - deviantart
      - flickr
      - "qwant images"
      - "startpage images"
      - startpage
      - artic

general:
  debug: false
  instance_name: "SearXNG"

search:
  safe_search: 2
  autocomplete: 'duckduckgo'
  formats:
    - html
  favicon_resolver: "allesedv"

server:
  # Is overwritten by ${SEARXNG_SECRET}
  secret_key: "ultrasecretkey"
  limiter: true
  image_proxy: true
  # public URL of the instance, to ensure correct inbound links. Is overwritten
  # by ${SEARXNG_BASE_URL}.
  # base_url: http://example.com/location

redis:
  # URL to connect redis database. Is overwritten by ${SEARXNG_REDIS_URL}.
  url: unix:///usr/local/searxng-redis/run/redis.sock?db=0

ui:
  static_use_hash: true
  theme_args:
    simple_style: black

# preferences:
#   lock:
#     - autocomplete
#     - method

engines:
    # for whatever reason, removing qwant like with
    # startpage/startpage images/etc above
    # will result in searxng failing to start
    #
    # qwant is being disabled due to captchas/timeouts,
    # not due to degeneracy like above
  - name: qwant
    disabled: true

#   - name: fdroid
#     disabled: false
#
#   - name: apk mirror
#     disabled: false
#
#   - name: mediathekviewweb
#     categories: TV
#     disabled: false
